### ISSUE TITLE
How to change the default theme used?

### ISSUE THREAD

**Issue by Strit** [manjaro/manjaro-kde-settings#3]
Hi all.

I would like to know how to change what default theme is getting used?

I have tried changing it in kdeglobals file and wallpaper in the org.kde.bla.bla.appletrc file. It does not work. It defaults to all stock KDE settings of breeze themes.

What I want to do, is change the default wallpaper to a custom one of mine, and the themes/icons/colors to Maia-Dark.
When booting the live CD and it doesn't work, I can set them manually, by going into settings.

**Comment by Kirek** [comment]
Can you post your kdeglobals and plasma-org.kde.plasma.desktop-appletsrc files?
Also, where do you put them? 
They should be at /etc/skel/.config/ or /etc/xdg

**Comment by Strit** [comment]
kdeglobals:
[code]
[ColorEffects:Disabled]
Color=56,56,56
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=1
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
Color=112,111,110
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
Enable=false
IntensityAmount=0
IntensityEffect=0

[Colors:Button]
BackgroundAlternate=77,77,77
BackgroundNormal=49,54,59
DecorationFocus=22,160,133
DecorationHover=22,160,133
ForegroundActive=61,174,233
ForegroundInactive=189,195,199
ForegroundLink=41,128,185
ForegroundNegative=218,68,83
ForegroundNeutral=246,116,0
ForegroundNormal=239,240,241
ForegroundPositive=39,174,96
ForegroundVisited=127,140,141

[Colors:Selection]
BackgroundAlternate=22,160,133
BackgroundNormal=22,160,133
DecorationFocus=22,160,133
DecorationHover=22,160,133
ForegroundActive=252,252,252
ForegroundInactive=239,240,241
ForegroundLink=253,188,75
ForegroundNegative=218,68,83
ForegroundNeutral=246,116,0
ForegroundNormal=239,240,241
ForegroundPositive=39,174,96
ForegroundVisited=189,195,199

[Colors:Tooltip]
BackgroundAlternate=77,77,77
BackgroundNormal=49,54,59
DecorationFocus=22,160,133
DecorationHover=22,160,133
ForegroundActive=61,174,233
ForegroundInactive=189,195,199
ForegroundLink=41,128,185
ForegroundNegative=218,68,83
ForegroundNeutral=246,116,0
ForegroundNormal=239,240,241
ForegroundPositive=39,174,96
ForegroundVisited=127,140,141

[Colors:View]
BackgroundAlternate=49,54,59
BackgroundNormal=35,38,41
DecorationFocus=22,160,133
DecorationHover=22,160,133
ForegroundActive=61,174,233
ForegroundInactive=189,195,199
ForegroundLink=41,128,185
ForegroundNegative=218,68,83
ForegroundNeutral=246,116,0
ForegroundNormal=239,240,241
ForegroundPositive=39,174,96
ForegroundVisited=127,140,141

[Colors:Window]
BackgroundAlternate=77,77,77
BackgroundNormal=49,54,59
DecorationFocus=22,160,133
DecorationHover=22,160,133
ForegroundActive=61,174,233
ForegroundInactive=189,195,199
ForegroundLink=41,128,185
ForegroundNegative=218,68,83
ForegroundNeutral=246,116,0
ForegroundNormal=239,240,241
ForegroundPositive=39,174,96
ForegroundVisited=127,140,141

[DesktopIcons]
ActiveColor=169,156,255
ActiveColor2=0,0,0
ActiveEffect=togamma
ActiveSemiTransparent=false
ActiveValue=0.699999988079071
Animated=true
DefaultColor=144,128,248
DefaultColor2=0,0,0
DefaultEffect=none
DefaultSemiTransparent=false
DefaultValue=1
DisabledColor=34,202,0
DisabledColor2=0,0,0
DisabledEffect=togray
DisabledSemiTransparent=true
DisabledValue=1
Size=48

[DialogIcons]
ActiveColor=169,156,255
ActiveColor2=0,0,0
ActiveEffect=none
ActiveSemiTransparent=false
ActiveValue=1
Animated=false
DefaultColor=144,128,248
DefaultColor2=0,0,0
DefaultEffect=none
DefaultSemiTransparent=false
DefaultValue=1
DisabledColor=34,202,0
DisabledColor2=0,0,0
DisabledEffect=togray
DisabledSemiTransparent=true
DisabledValue=1
Size=32

[General]
ColorScheme=Maia Dark
Name=Maia
XftAntialias=true
XftHintStyle=hintmedium
XftSubPixel=none
shadeSortColumn=true

[Icons]
Theme=maia-dark

[KDE]
ShowDeleteCommand=false
contrast=7

[KFileDialog Settings]
Automatically select filename extension=true
Breadcrumb Navigation=true
Decoration position=0
LocationCombo Completionmode=5
PathCombo Completionmode=5
Previews=false
Show Bookmarks=false
Show Full Path=false
Show Preview=false
Show Speedbar=true
Show hidden files=false
Sort by=Name
Sort directories first=true
Sort reversed=false
Speedbar Width=133
View Style=Simple
listViewIconSize=0

[MainToolbarIcons]
ActiveColor=169,156,255
ActiveColor2=0,0,0
ActiveEffect=none
ActiveSemiTransparent=false
ActiveValue=1
Animated=false
DefaultColor=144,128,248
DefaultColor2=0,0,0
DefaultEffect=none
DefaultSemiTransparent=false
DefaultValue=1
DisabledColor=34,202,0
DisabledColor2=0,0,0
DisabledEffect=togray
DisabledSemiTransparent=true
DisabledValue=1
Size=22

[PanelIcons]
ActiveColor=169,156,255
ActiveColor2=0,0,0
ActiveEffect=togamma
ActiveSemiTransparent=false
ActiveValue=0.699999988079071
Animated=false
DefaultColor=144,128,248
DefaultColor2=0,0,0
DefaultEffect=none
DefaultSemiTransparent=false
DefaultValue=1
DisabledColor=34,202,0
DisabledColor2=0,0,0
DisabledEffect=togray
DisabledSemiTransparent=true
DisabledValue=1
Size=32

[PreviewSettings]
MaximumRemoteSize=0

[SmallIcons]
ActiveColor=169,156,255
ActiveColor2=0,0,0
ActiveEffect=none
ActiveSemiTransparent=false
ActiveValue=1
Animated=false
DefaultColor=144,128,248
DefaultColor2=0,0,0
DefaultEffect=none
DefaultSemiTransparent=false
DefaultValue=1
DisabledColor=34,202,0
DisabledColor2=0,0,0
DisabledEffect=togray
DisabledSemiTransparent=true
DisabledValue=1
Size=16

[ToolbarIcons]
ActiveColor=169,156,255
ActiveColor2=0,0,0
ActiveEffect=none
ActiveSemiTransparent=false
ActiveValue=1
Animated=false
DefaultColor=144,128,248
DefaultColor2=0,0,0
DefaultEffect=none
DefaultSemiTransparent=false
DefaultValue=1
DisabledColor=34,202,0
DisabledColor2=0,0,0
DisabledEffect=togray
DisabledSemiTransparent=true
DisabledValue=1
Size=22

[WM]
activeBackground=49,54,59
activeBlend=255,255,255
activeForeground=239,240,241
inactiveBackground=49,54,59
inactiveBlend=75,71,67
inactiveForeground=127,140,141
[/code]

plasma-org.kde.desktop-appletsrc:
[code]
[ActionPlugins][0]
MidButton;NoModifier=org.kde.paste
RightButton;NoModifier=org.kde.contextmenu
wheel:Vertical;NoModifier=org.kde.switchdesktop

[ActionPlugins][1]
MidButton;NoModifier=org.kde.paste
RightButton;NoModifier=org.kde.contextmenu

[ActionPlugins][129]
MidButton;NoModifier=org.kde.paste
RightButton;NoModifier=org.kde.contextmenu
wheel:Vertical;NoModifier=org.kde.switchdesktop

[Containments][1]
activityId=
formfactor=2
immutability=1
lastScreen=0
location=4
plugin=org.kde.panel
wallpaperplugin=org.kde.image

[Containments][1][Applets][2]
immutability=1
plugin=org.kde.plasma.kickoff

[Containments][1][Applets][2][Configuration][General]
favorites=org.kde.dolphin.desktop,org.kde.konsole.desktop,systemsettings.desktop

[Containments][1][Applets][2][Configuration][Shortcuts]
global=Alt+F1

[Containments][1][Applets][2][Shortcuts]
global=Alt+F1

[Containments][1][Applets][3]
immutability=1
plugin=org.kde.plasma.pager

[Containments][1][Applets][4]
immutability=1
plugin=org.kde.plasma.icontasks

[Containments][1][Applets][4][Configuration][General]
launchers=file:///usr/share/applications/org.kde.dolphin.desktop?wmClass=dolphin,file:///usr/share/applications/qupzilla.desktop?wmClass=QupZilla

[Containments][1][Applets][5]
immutability=1
plugin=org.kde.plasma.showdesktop

[Containments][1][Applets][6]
immutability=1
plugin=org.kde.plasma.trash

[Containments][1][Applets][7]
immutability=1
plugin=org.kde.plasma.systemtray

[Containments][1][Applets][7][Configuration]
SystrayContainmentId=8

[Containments][1][Applets][7][Configuration][Containments][8]
formfactor=2
location=4

[Containments][1][Applets][8]
immutability=1
plugin=org.kde.plasma.digitalclock

[Containments][1][General]
AppletOrder=2;3;4;6;7;8

[Containments][35]
activityId=1f7eb98a-739d-43f8-8def-a6fcf4b7f173
formfactor=0
immutability=1
lastScreen=0
location=0
plugin=org.kde.desktopcontainment
wallpaperplugin=org.kde.image

[Containments][35][ConfigDialog]
DialogHeight=540
DialogWidth=720

[Containments][35][Wallpaper][org.kde.image][General]
Image=file:///usr/share/backgrounds/manjaro-strit.jpg
height=983
width=1920

[Containments][8]
activityId=
formfactor=2
immutability=1
lastScreen=0
location=4
plugin=org.kde.plasma.private.systemtray
wallpaperplugin=org.kde.image

[Containments][8][Applets][36]
immutability=1
plugin=org.kde.plasma.notifications

[Containments][8][Applets][37]
immutability=1
plugin=org.kde.plasma.devicenotifier

[Containments][8][Applets][38]
immutability=1
plugin=org.kde.plasma.volume

[Containments][8][Applets][39]
immutability=1
plugin=org.kde.plasma.clipboard

[Containments][8][Applets][40]
immutability=1
plugin=org.kde.plasma.battery

[Containments][8][Applets][41]
immutability=1
plugin=org.kde.plasma.networkmanagement

[Containments][8][General]
extraItems=org.kde.plasma.battery,org.kde.plasma.bluetooth,org.kde.plasma.clipboard,org.kde.plasma.devicenotifier,org.kde.plasma.mediacontroller,org.kde.plasma.networkmanagement,org.kde.plasma.notifications,org.kde.plasma.volume
knownItems=org.kde.plasma.battery,org.kde.plasma.bluetooth,org.kde.plasma.clipboard,org.kde.plasma.devicenotifier,org.kde.plasma.mediacontroller,org.kde.plasma.networkmanagement,org.kde.plasma.notifications,org.kde.plasma.volume
[/code]

Both are placed in /etc/skel/.config/

**Comment by Strit** [comment]
No idea why it does not work or what I need to change to set the default theme on the ISO?
